// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func navigationMenu() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"bg-white shadow-md p-4 border-b border-gray-200 flex flex-row overflow-x-auto\"><ul class=\"flex flex-row space-x-4 max-w-4xl w-full mx-auto \"><li class=\"flex-shrink-0\"><button class=\"block w-full text-left py-2 px-4 rounded-lg transition-all duration-200 ease-in-out\n                           bg-blue-500 text-white shadow-md\" onclick=\"alert(&#39;Navigate to Manage Trades&#39;)\">Manage Trades</button></li><li class=\"flex-shrink-0\"><button class=\"block w-full text-left py-2 px-4 rounded-lg transition-all duration-200 ease-in-out\n                           text-gray-700 hover:bg-gray-100 hover:text-blue-600\" onclick=\"alert(&#39;Navigate to Cost Basis&#39;)\">Cost Basis</button></li><li class=\"flex-shrink-0\"><button class=\"block w-full text-left py-2 px-4 rounded-lg transition-all duration-200 ease-in-out\n                           text-gray-700 hover:bg-gray-100 hover:text-blue-600\" onclick=\"alert(&#39;Navigate to FIF Calculation&#39;)\">FIF Calculation</button></li><li class=\"flex-shrink-0\"><button class=\"block w-full text-left py-2 px-4 rounded-lg transition-all duration-200 ease-in-out\n                           text-gray-700 hover:bg-gray-100 hover:text-blue-600\" onclick=\"alert(&#39;Navigate to FIF Report&#39;)\">FIF Report</button></li></ul></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
